version: '1'
services:
  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - backend
  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - 8000:8000