# # Dockerfile del backend
# FROM python:3.12.3

# WORKDIR /app

# COPY requirements.txt ./

# RUN pip install -r requirements.txt

# COPY . .

# EXPOSE 8000

# RUN python manage.py makemigrations

# RUN python manage.py migrate

# # CMD celery -A backend worker -l INFO && python manage.py runserver 0.0.0.0:8000
# CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]

FROM python:3.12.3

WORKDIR /app

# Copiar archivos de la aplicación
COPY requirements.txt ./

# Instalar dependencias
RUN pip install -r requirements.txt

COPY . .

# Instalar supervisord
RUN apt-get update && apt-get install -y supervisor

# Copiar el archivo de configuración supervisord
COPY supervisord.conf /etc/supervisor/conf.d/supervisord.conf

# Ejecutar supervisord
CMD ["supervisord", "-n"]