# Generated by Django 5.0.4 on 2024-04-27 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processDataApp', '0002_batchdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('likes', models.IntegerField()),
                ('comments', models.IntegerField()),
                ('shares', models.IntegerField()),
                ('reactions', models.IntegerField()),
                ('emotions', models.TextField()),
                ('sentiments', models.TextField()),
                ('processed', models.BooleanField()),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processDataApp.batchdata')),
            ],
        ),
    ]
